### ISSUE TITLE
when install apks in threading ,there is an adbInstallError happend.

### ISSUE THREAD

**Issue by bs111** [openatx/adbutils#10]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "D:\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "D:\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "G:/MyPython/Studty/65-多媒体-图片操作/21 循环重启判断systemui Launcher是否正常显示.py", line 116, in install
    device.install(apk_path=apk_loaction)
  File "D:\Python36\lib\site-packages\adbutils\mixin.py", line 126, in install
    self.install_remote(dst, clean=True)
  File "D:\Python36\lib\site-packages\adbutils\mixin.py", line 144, in install_remote
    raise AdbInstallError(output)
adbutils.errors.AdbInstallError: cmd: Failure calling service package: Broken pipe (32)

**Comment by codeskyblue** [comment]
请提供demo代码
