### ISSUE TITLE
is it support code to run "screencap -p"?

### ISSUE THREAD

**Issue by brianwynne1** [openatx/adbutils#7]
the device is connected, when run i get this, please help, thx :D

```
from adbutils import adb

out = adb.connect("127.0.0.1:62026")
d = adb.device()
return d.adb_output("screencap -p")
```
```
Traceback (most recent call last):
  File "D:\App\Python\Python37-32\lib\site-packages\adbutils\__init__.py", line 312, in adb_output
    return subprocess.check_output(cmdline, stderr=subprocess.STDOUT, shell=True).decode('utf-8')
  File "D:\App\Python\Python37-32\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "D:\App\Python\Python37-32\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'D:\App\Android\SDK\platform-tools\adb.EXE -s 127.0.0.1:62026 "screencap -p"' returned non-zero exit status 1.
```

**Comment by QGB** [comment]
@brianwynne1 
nox Emulator
