### ISSUE TITLE
AttributeError: module 're' has no attribute 'Pattern'

### ISSUE THREAD

**Issue by ufo105** [openatx/adbutils#82]
平台：ubuntu 18.04 
python：python3.6.9
导入adbutils库报错如下：
>>> import adbutils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/realeasy/.local/lib/python3.6/site-packages/adbutils/__init__.py", line 14, in <module>
    from ._device import AdbDevice, Sync
  File "/home/realeasy/.local/lib/python3.6/site-packages/adbutils/_device.py", line 49, in <module>
    class BaseDevice:
  File "/home/realeasy/.local/lib/python3.6/site-packages/adbutils/_device.py", line 352, in BaseDevice
    command: str = "logcat -v time") -> StopEvent:
AttributeError: module 're' has no attribute 'Pattern'

**Comment by PythonTryHard** [comment]
@ufo105 Your Python is too old. `re.Pattern` was introduced in Python 3.7. @codeskyblue Any way to mark this package to be minimum Python 3.7?

**Comment by codeskyblue** [comment]
@PythonTryHard thanks, limited python version in setup.py with adbutils version 1.2.2

**Comment by exzhawk** [comment]
@codeskyblue and now whoever install this package with python 3.6 will get version 1.2.1 and it won't work
and this line should be changed https://github.com/openatx/adbutils/blob/5787ac36c99ebfd7100e70a093da2fa30f5a1378/README.md?plain=1#L4

**Comment by codeskyblue** [comment]
@exzhawk  I add a new version 1.2.10 for python 3.6, check if this version works

**Comment by codeskyblue** [comment]
1.2.10 was removed, use 1.2.11, which only limit to python3.6
